// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.cg.grpc;

public interface requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cg.grpc.request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   */
  long getTimestamp();
}
